name: CompileTest

on: [pull_request, push]

jobs:
  build_on_Ubuntu:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install HDF5
      run: |
       sudo apt-get update
       sudo apt-get install libhdf5-103 libhdf5-cpp-103 libhdf5-dev libhdf5-openmpi-103
    - name: Configure CMake
      run: cmake ./
    - name: Build
      run: make all
  build_on_MacOs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install HDF5
      run: |
       brew update
       brew install hdf5
    - name: Configure CMake
      run: cmake ./
    - name: Build
      run: make all