name: Docs

on:
  #push:
  #  branches-ignore:
  #    - '**'
  push:
    branches: [ master , dev/Documentation]
  pull_request:
    branches: [ master , dev/Documentation]

jobs:
  build_on_Ubuntu:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install doxygen graphviz libhdf5-103 libhdf5-cpp-103 libhdf5-dev libhdf5-openmpi-103
      - name: Configure CMake
        run: cmake ./
      - name: Build Documentation
        run: make docs
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: doc/gh-pages # The branch the action should deploy to.
          FOLDER: docs_doxygen/html # The folder the action should deploy.